### ISSUE TITLE
NullPointerException in Arja filter

### ISSUE THREAD

**Issue by khaes-kth** [SpoonLabs/coming#177]
When executed in repairability mode on [react-native](https://github.com/facebook/react-native) project, a NullPointerException is thrown. Here is the stack trace:
```
Exception in thread "main" java.lang.NullPointerException
	at spoon.support.reflect.declaration.CtElementImpl.filterChildren(CtElementImpl.java:353)
	at spoon.support.reflect.declaration.CtElementImpl.getElements(CtElementImpl.java:338)
	at fr.inria.coming.repairability.repairtools.Arja.filter(Arja.java:93)
	at fr.inria.coming.repairability.RepairabilityAnalyzer.analyze(RepairabilityAnalyzer.java:66)
	at fr.inria.coming.core.engine.RevisionNavigationExperiment.analyze(RevisionNavigationExperiment.java:121)
	at fr.inria.coming.main.ComingMain.start(ComingMain.java:152)
	at fr.inria.coming.main.ComingMain.run(ComingMain.java:145)
	at fr.inria.coming.main.ComingMain.main(ComingMain.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by martinezmatias** [comment]
Hi @khaes-kth 
Thanks for reporting the issue.
If possible, you could create a test case for exposing this issue?
Thanks
Matias

**Comment by khaes-kth** [comment]
[This branch](https://github.com/khaes-kth/coming/tree/test-null-pointer-exception) contains a [new test case ](https://github.com/khaes-kth/coming/blob/56981a0ab33bce397b8991dc92cbb80669668374/src/test/java/fr/inria/coming/spoon/repairability/RepairabilityTest.java#L206) based on a [new change pair](https://github.com/khaes-kth/coming/tree/test-null-pointer-exception/src/main/resources/repairability_test_files/other/ReactDrawerLayoutManager_1d0b39/ReactDrawerLayoutManager_1d0b39).
The test case fails because a NullPointerException is thrown when it is called.

**Comment by khaes-kth** [comment]
Hello again,

I found that the problem occurs because `factory  is null in [this line ](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/reflect/declaration/CtElementImpl.java#L364)when `CtElementImpl.filterChildren` method is being executed. Do you know in which cases `factory` is null?

**Comment by monperrus** [comment]
@khaes-kth will try to make a PR on gumtree-spoon to fix that one

**Comment by khaes-kth** [comment]
The problem was caused by Gumtree and it is solved [here](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/115). However, the new version of Gumtree should be used in pom.xml file.

**Comment by martinezmatias** [comment]
Hi @khaes-kth 
Thanks! 

> The problem was caused by Gumtree and it is solved here

Very minor comment: you have fixed GumTreeSpoonDiff (i.e., the project that combines GumTree and Spoon). The GumTree "core" is in another repo [here](https://github.com/GumTreeDiff/gumtree) )

**Comment by martinezmatias** [comment]
> However, the new version of Gumtree should be used in pom.xml file.

Perfect. GumTreeSpoonDiff must be automatically deployed on Maven central. So, when that happens we can upgrade the dependency.

**Comment by khaes-kth** [comment]
Hi @martinezmatias ,



> Very minor comment: you have fixed GumTreeSpoonDiff

Yes, you are right. Actually, at first, I thought I should fix GumTree but then realized that GumTreeSpoonDiff should be fixed.



> when that happens we can upgrade the dependency

Great! I will do so.

Thanks

**Comment by khaes-kth** [comment]
Fixed [here](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/pull/115#issuecomment-545415355)
