### ISSUE TITLE
IOException thrown when filespair input mode is used in windows

### ISSUE THREAD

**Issue by khaes-kth** [SpoonLabs/coming#193]
When `MainComingTest.testFilePairsMain()` is run on Windows, an IOException is thrown:

```
java.lang.RuntimeException: The filename, directory name, or volume label syntax is incorrect
	at spoon.compiler.builder.SourceOptions.sources(SourceOptions.java:67)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:404)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:372)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:340)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:123)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:106)
	at gumtree.spoon.AstComparator.getCtType(AstComparator.java:114)
	at gumtree.spoon.AstComparator.getCtType(AstComparator.java:134)
	at gumtree.spoon.AstComparator.compare(AstComparator.java:91)
	at fr.inria.coming.changeminer.analyzer.DiffEngineFacade.compareContent(DiffEngineFacade.java:34)
	at fr.inria.coming.changeminer.analyzer.commitAnalyzer.FineGrainDifftAnalyzer.compare(FineGrainDifftAnalyzer.java:136)
	at fr.inria.coming.changeminer.analyzer.commitAnalyzer.FineGrainDifftAnalyzer.analyze(FineGrainDifftAnalyzer.java:75)
	at fr.inria.coming.changeminer.analyzer.commitAnalyzer.FineGrainDifftAnalyzer.analyze(FineGrainDifftAnalyzer.java:118)
	at fr.inria.coming.core.engine.RevisionNavigationExperiment.analyze(RevisionNavigationExperiment.java:123)
	at fr.inria.coming.main.ComingMain.start(ComingMain.java:152)
	at fr.inria.coming.main.ComingMain.run(ComingMain.java:145)
	at fr.inria.coming.spoon.core.MainComingTest.testFilePairsMain(MainComingTest.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at java.io.File.createTempFile(File.java:2070)
	at spoon.compiler.builder.SourceOptions.sources(SourceOptions.java:62)
	... 39 more
```

The problem seems to occur [here](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/compiler/builder/SourceOptions.java#L51) when `source.getName()` returns something like "`1205753_EmbedPooledConnection_0_s.java->1205753_EmbedPooledConnection_0_t.java`". The problem should be caused by the "`->`" character in this string.

**Comment by martinezmatias** [comment]
Hi @khaes-kth 
I will take a look to this problem.
Thanks for reporting it.
Regards
Matias

**Comment by khaes-kth** [comment]
Hi @martinezmatias 
Thanks for considering it.

**Comment by martinezmatias** [comment]
PR #194  should fix this problem (only reproducible on Windows).

**Comment by khaes-kth** [comment]
Hi @martinezmatias 
Yes, it is solved. Thanks.
