### ISSUE TITLE
Problems with Java 11

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/coming#222]
When I executed on a JVM 11, I got:

```
	at spoon.support.StandardEnvironment.<init>(StandardEnvironment.java:100)
	at gumtree.spoon.AstComparator.createFactory(AstComparator.java:84)
	at gumtree.spoon.AstComparator.getCtType(AstComparator.java:126)
	at gumtree.spoon.AstComparator.getCtType(AstComparator.java:151)
	at gumtree.spoon.AstComparator.compare(AstComparator.java:108)
	at fr.inria.coming.changeminer.analyzer.commitAnalyzer.FineGrainDifftAnalyzer.compare(FineGrainDifftAnalyzer.java:139)
	at fr.inria.coming.changeminer.analyzer.commitAnalyzer.FineGrainDifftAnalyzer.analyze(FineGrainDifftAnalyzer.java:81)
	at fr.inria.coming.changeminer.analyzer.commitAnalyzer.FineGrainDifftAnalyzer.analyze(FineGrainDifftAnalyzer.java:121)
	at fr.inria.coming.core.engine.RevisionNavigationExperiment.analyze(RevisionNavigationExperiment.java:127)
	at fr.inria.coming.main.ComingMain.start(ComingMain.java:147)
	at fr.inria.coming.main.ComingMain.run(ComingMain.java:140)
	at fr.inria.coming.main.ComingMain.main(ComingMain.java:124)
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
	at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:555)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:580)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:567)
	at spoon.Launcher.<clinit>(Launcher.java:589)
	... 12 more
```

JVM info:

```
java version "11.0.7" 2020-04-14 LTS
```

**Comment by monperrus** [comment]
Per https://github.com/SpoonLabs/coming/pull/257, Coming now uses Java 17, based on latest spoon and gumtree-spoon.
