### ISSUE TITLE
Program Features For Local Java Project

### ISSUE THREAD

**Issue by neelofarhassan** [SpoonLabs/coming#234]
Is there any way to extract features of a class in a checkout project without using git source and target? 
As an example, If I want to extract features for AnnotationUtils from Lang(Lang1f) project in defects4j cloned on my local disk, would this command work?

java -classpath coming.jar fr.inria.coming.main.ComingMain -input files -location  /home/software-testing/fault-localization/defects4j-data/Lang/Lang-1f/src/main/java/org/apache/commons/lang3/AnnotationUtils.java

I am getting this error
and this is the error message
log4j:WARN File option not set for appender [file].
log4j:WARN Are you using FileAppender instead of ConsoleAppender?
Exception in thread "main" java.lang.NullPointerException
at fr.inria.coming.core.engine.files.FileDynamicIterator.<init>(FileDynamicIterator.java:31)
at fr.inria.coming.core.engine.files.FileNavigationExperiment.<init>(FileNavigationExperiment.java:30)
at fr.inria.coming.core.engine.files.FileNavigationExperiment.<init>(FileNavigationExperiment.java:21)
at fr.inria.coming.main.ComingMain.loadInput(ComingMain.java:257)
at fr.inria.coming.main.ComingMain.createEngine(ComingMain.java:216)
at fr.inria.coming.main.ComingMain.run(ComingMain.java:132)
at fr.inria.coming.main.ComingMain.main(ComingMain.java:124)

Furthermore, I couldn't find any documentation on how to decode/read the features.json file. Is there any help available on this which I missed?

Thanks,
Neelofar

**Comment by monperrus** [comment]
> Is there any way to extract features of a class in a checkout project without using git source and target?

yes, using mode "filespair", `-mode filespair -location <source_file_path>:<target_file_path>` eg `-mode filespair -location Foo_s.java:Foo_t.java` see README
