### ISSUE TITLE
request for readme.md example usage "filtervalue" fix

### ISSUE THREAD

**Issue by inkuxuan** [SpoonLabs/coming#249]
in line 451 of readme.md, the example goes

> -filter keywords **filtervalue** [MATH- 

While the parameter instructions (line 49) goes

>  **-filtervalue** <arg>  

And I think only `-filtervalue` works because if I pass `filtervalue` as a parameter, it throws `NullPointerException` at `fr.inria.coming.core.filter.commitmessage.KeyWordsMessageFilter#accept(Commit c)` (line 36)

**Comment by martinezmatias** [comment]
Hi @inkuxuan 

Could you create a Pull Request with a test that exposes the wrong behaviour?
Thanks
Matias

**Comment by inkuxuan** [comment]
@martinezmatias 

Sorry but I was only able to build the project using Maven. Opening this project in my IDE will end up with Maven failing to download dependencies. Thus I am unable to modify and create a new test case.
I can give further information about the run though.

Microsoft Windows version `10.0.19042.1052`

Java version output:

> java version "1.8.0_241"
> Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
> Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

Command line:

>java -classpath ./coming-with-dep.jar fr.inria.coming.main.ComingMain -location ../commons-math/ -mode mineinstance -pattern ./pattern_specification/pattern_DEL_IF_RET.xml -filter keywords filtervalue MATH- -output ./out

in which `coming-with-dep.jar` is the build output by `mvn install -DskipTests`;
 `../commons-math/` is the git repository cloned from https://github.com/apache/commons-math;
`./pattern_specification` directory has the same content as `coming/src/main/resources/pattern_specification`

The run will end up with the following lines of output:

> Analyzing 6700/6799 1b7f10eed7ad4548b85e1449686206332ab4a78c
> Exception in thread "main" java.lang.NullPointerException
>         at java.lang.String.contains(Unknown Source)
>         at fr.inria.coming.core.filter.commitmessage.KeyWordsMessageFilter.accept(KeyWordsMessageFilter.java:36)
>         at fr.inria.coming.core.filter.commitmessage.KeyWordsMessageFilter.accept(KeyWordsMessageFilter.java:11)
>         at fr.inria.coming.core.engine.RevisionNavigationExperiment.accept(RevisionNavigationExperiment.java:160)
>         at fr.inria.coming.core.engine.RevisionNavigationExperiment.analyze(RevisionNavigationExperiment.java:120)
>         at fr.inria.coming.main.ComingMain.start(ComingMain.java:147)
>         at fr.inria.coming.main.ComingMain.run(ComingMain.java:140)
>         at fr.inria.coming.main.ComingMain.main(ComingMain.java:124)
