### ISSUE TITLE
error in run Coming

### ISSUE THREAD

**Issue by malikam2001** [SpoonLabs/coming#252]
hi

I put the jar file" coming-0-SNAPSHOT-jar-with-dependencies.jar" inside Coming Folder instead of folder "coming/target"
I tried to run it again I got this error

malikhudaib@Maliks-MacBook-Pro coming % java -classpath ./coming-0-SNAPSHOT-jar-with-dependencies.jar fr.inria.coming.main.ComingMain -location ./repogit4testv0/ -mode mineinstance -action INS -entitytype Method -output ./out
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: (No such file or directory)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
at java.base/java.io.FileOutputStream.(FileOutputStream.java:235)
at java.base/java.io.FileOutputStream.(FileOutputStream.java:155)
at org.apache.log4j.FileAppender.setFile(FileAppender.java:290)
at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:194)
at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:164)
at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:257)
at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:133)
at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:97)
at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:689)
at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:647)
at org.apache.log4j.PropertyConfigurator.parseCatsAndRenderers(PropertyConfigurator.java:568)
at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:442)
at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:476)
at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:471)
at org.apache.log4j.LogManager.(LogManager.java:125)
at org.apache.log4j.Logger.getLogger(Logger.java:105)
at fr.inria.coming.main.ComingMain.(ComingMain.java:57)
NOT_EXECUTED_BY_TRAVIS
2022-01-26 12:37:54,456 INFO fr.inria.coming.core.engine.filespair.FilePairsDiff -

Analyzing 1/13 60b54977abe45f662daaa80ebfdf63ab4fe3a9b2
2022-01-26 12:37:54,459 INFO fr.inria.coming.changeminer.analyzer.commitAnalyzer.FineGrainDifftAnalyzer -

Commit: 60b54977abe45f662daaa80ebfdf63ab4fe3a9b2
2022-01-26 12:37:54,459 INFO fr.inria.coming.core.engine.filespair.FilePairsDiff -

Analyzing 2/13 ab71649c481971a9ad54f04797f5fd9cb133789b
2022-01-26 12:37:54,465 INFO fr.inria.coming.changeminer.analyzer.commitAnalyzer.FineGrainDifftAnalyzer -

Commit: ab71649c481971a9ad54f04797f5fd9cb133789b
2022-01-26 12:37:54,474 INFO fr.inria.coming.core.engine.filespair.FilePairsDiff -

Analyzing 3/13 8d94514f4d888b7b4e8abd0d77b974a0c8e3baad
2022-01-26 12:37:54,475 INFO fr.inria.coming.changeminer.analyzer.commitAnalyzer.FineGrainDifftAnalyzer -

Commit: 8d94514f4d888b7b4e8abd0d77b974a0c8e3baad
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.ExceptionInInitializerError
at spoon.support.StandardEnvironment.(StandardEnvironment.java:100)
at gumtree.spoon.AstComparator.createFactory(AstComparator.java:84)
at gumtree.spoon.AstComparator.getCtType(AstComparator.java:126)
at gumtree.spoon.AstComparator.getCtType(AstComparator.java:151)
at gumtree.spoon.AstComparator.compare(AstComparator.java:108)
at fr.inria.coming.changeminer.analyzer.commitAnalyzer.FineGrainDifftAnalyzer.compare(FineGrainDifftAnalyzer.java:139)
at fr.inria.coming.changeminer.analyzer.commitAnalyzer.FineGrainDifftAnalyzer.analyze(FineGrainDifftAnalyzer.java:81)
at fr.inria.coming.changeminer.analyzer.commitAnalyzer.FineGrainDifftAnalyzer.analyze(FineGrainDifftAnalyzer.java:121)
at fr.inria.coming.core.engine.RevisionNavigationExperiment.analyze(RevisionNavigationExperiment.java:127)
at fr.inria.coming.main.ComingMain.start(ComingMain.java:147)
at fr.inria.coming.main.ComingMain.run(ComingMain.java:140)
at fr.inria.coming.main.ComingMain.main(ComingMain.java:124)
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:555)
at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:580)
at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:567)
at spoon.Launcher.(Launcher.java:589)
... 12 more
malikhudaib@Maliks-MacBook-Pro coming %

<img width="1440" alt="Screenshot 2022-01-26 at 12 37 20" src="https://user-images.githubusercontent.com/56842591/151172530-1d440a99-e1cd-4bd7-b00e-b0e691ddee97.png">

**Comment by malikam2001** [comment]
anybody can help in this issue please

**Comment by monperrus** [comment]
this is due to error in configuring the logging, see stacktrace line `org.apache.log4j`
